### ISSUE TITLE
can't build Object through spritesheet.csv and  spritesheet.png => ERROR - attribute name is not unique

### ISSUE THREAD

**Issue by 1500256797** [cryptopunksnotdead/punks.spritesheet#1]
when running this code, it doesn't work
```
@builtin ||= Pixelart::Spritesheet.read(  image_path, meta_path, width:  24, height: 24 )
```

!!! ERROR - attribute name is not unique:
#<Pixelart::Metadata::Sprite:0x00000215e69efe78
 @id=302,
 @more_names=[],
 @name="3D Glasses",
 @type="Attribute">
duplicate:
#<Pixelart::Metadata::Sprite:0x00000215e69f4040
 @id=301,
 @more_names=[],
 @name="3D Glasses",
duplicate:

**Comment by geraldb** [comment]
Please, post to the public forum => https://old.reddit.com/r/DIYPunkArt
